### PR TITLE
Added post-survey template

### PR DESCRIPTION
**Pull request by ajparsons**
Implements the delayed user survey descripted in #69 

Anticipating some corrections about narrowing down the scope of where it appears, or switching to our rather than mailchimp styling but:

For every post or page will put this at the bottom:

image

This form contains a populated parameter for the page it came from.

### CODE REVIEW

**Review by zarino — COMMENTED** [review]
Don’t think we need to use the Mailchimp CSS. Also, a few things that could be better about the markup (eg: using a `<label>` rather than placeholder). How about this:

```html
<div class="p-3 p-md-4 my-5 rounded has-yellow-100-background-color">
  <h3><small class="d-block">Survey:</small> Can we ask you later how you're doing?</h3>
  <p>Let us know your email address, and we'll follow up in a few weeks' time, to see whether there's been any progress on your issue, and to get your thoughts on how we can make FixMyBlock more helpful.</p>
  <div id="mc_embed_signup">
    <form action="<?= $survey_url ?>" class="validate" id="mc-embedded-subscribe-form" method="post" name="mc-embedded-subscribe-form" novalidate="" target="_blank">
      <label for="mce-EMAIL">Your email address</label>
      <div id="mc_embed_signup_scroll" class="d-lg-flex">
        <input id="mce-EMAIL" name="EMAIL" required="" type="email" value="" class="form-control">
        <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
        <div aria-hidden="true" style="position: absolute; left: -5000px;">
          <input name="b_53d0d2026dea615ed488a8834_9334858efa" tabindex="-1" type="text" value="">
        </div>
        <div class="mt-3 mt-lg-0 ml-lg-3">
          <input id="mc-embedded-subscribe" name="subscribe" type="submit" class="btn btn-primary" value="Sign up for survey">
        </div>
      </div>
    </form>
  </div>
</div>
```

image

Two other thoughts:
1. Most pages have a long list of "related guides" at the end, and right now this form will appear _after_ all of those. Is it that too late?
2. Semi-related: Is hard-coding this form as an include in `singular.php` is the best solution? Should we instead make it into a shortcode and a Block? That would mean WordPress admins could decide to include it exactly where it currently is (via the `post-content-sidebar` widget area in WordPress Admin > Appearance > Widgets) and/or also _in the middle_ of posts (via the Block editor)?

**Comment by ajparsons** [comment]
I think the answer is "yes" to all of that. it would be better as a block, I was just trying to avoid having to edit all the pages (but also that's fine). Are blocks/shortcodes managed in the repo or in the admin page? Point me in the right direction and I can give it a go.

**Comment by zarino** [comment]
> Are blocks/shortcodes managed in the repo or in the admin page?

In the repo. Here’s a list of all the custom blocks we’ve created in the theme so far:

https://github.com/mysociety/fixmyblock-wordpress/tree/master/fixmyblock-theme/blocks

We’re using the Carbon Fields framework to reduce the boilerplate around creating our own blocks. We call `Block::make(…)` with a bunch of configuration options, and then it defines the block and makes it available to users in the Editor.

If we want to _also_ make it available as a shortcode (useful when you want to insert the "block" into places that don’t support the Block editor, like textareas widgets in a sidebar) you’ll want to use `add_shortcode(…)`, like this:

https://github.com/mysociety/orgsites/blob/5a986fef901b0c2942616d4b97abb62a035249b8/blogs/themes/mysociety-new/includes/shortcode-donate.php

Let me know if you’d like to work on this together. (Or if you’d rather I just did it!)

**Comment by ajparsons** [comment]
I think probably don't need a short code if the blocks are how all the information pages are working.

I think if you're able to do the block change that would be really great (but if you're not going to have time soon, I can try and figure it out! Just keen to start trying if this is going to get responses or if I need to try something else).  I can then go and put it in a few pages and see how that's going.

**Comment by zarino** [comment]
@ajparsons I‘ve pushed a commit that turns the template into a Block and a Widget, so it can either be included individually in the main content of any page, or can be added to any of the "widget areas" on the site (eg: at the end of every page, via the "Posts and pages: after content") in a single go.

**Pull request merged**
